FROM jetbrains/teamcity-agent:2017.2.2

# Make sure github.com is a known host when git is using SSH
RUN mkdir -p /etc/ssh
RUN ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts
COPY add-host.sh /usr/local/bin/
