// ChangeFileTimePS.idl : IDL source for ChangeFileTimePS.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (ChangeFileTimePS.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(5FC4D8AB-F704-407C-9E69-CAC0FC0F982E),
		dual,
		helpstring("IChangeFileTimeHandler Interface"),
		pointer_default(unique)
	]
	interface IChangeFileTimeHandler : IDispatch
	{
	};

[
	uuid(D3C346F6-8B3E-4A06-B752-CD44F596D8DD),
	version(1.0),
	helpstring("ChangeFileTimePS 1.0 Type Library")
]
library CHANGEFILETIMEPSLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(6736099C-D4FA-4006-8B89-223BC5BAA967),
		helpstring("ChangeFileTimeHandler Class")
	]
	coclass ChangeFileTimeHandler
	{
		[default] interface IChangeFileTimeHandler;
	};
};
