language: csharp
solution: Games.sln
install:
  - nuget restore Games.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Games.sln
#  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Games.Tests/bin/Release/Games.Tests.dll
