language: node_js
sudo: false
node_js:
- lts/*
after_success:
- npm run coveralls
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: Nikolaos.Georgiou@gmail.com
  api_key:
    secure: tB1YeAUckUhhqkAnEEs4CBlTMWqVEsg8EndYbVmhHfqgqhcpEUWSYzuH3ayptgP87rGt+sAeh7TAxDow+bfUPwBiMg7fqIykRXne9++xIoSYPf81Ow3FagLiYGo1VAXie2TV/Bw0f8EbwO6UiQrT3h1FA4rWmgDADtYm2Rz2nQzIrYwzTPg+Pu20Oq0vLDa5/ohVEseCULWCtoBfuxQCjS2m9JMDYCNr/LbMl78o7JAHYRRpwV+sGLHH1eKQHm7FuWpdBcU7V/15ltgIReWujhY8EDG0/1liHE0CakWOyMcBt8Q2K45zGKVLfx7+c1xLKkkTMOIgsWQ2pDDhf0qQyfz8DLJOpe5O/vVBcc/QD2HRIr15CPzdxgO2e/wGr/hvMVwxqQIUkK8dG7fX5xnJq8WBx2NfHNAEHDAIrjBBwubWOeytMRBqr9zRe087jJDX3pCKG7tdl02/3RKhZMfq+7ivKCQZqSmX8vhIATVaiCw3WFBStv9yw99jqDz9D9XKGgEAdDsk5xQOKCNPnmdg+PooCtw9Choe4s+NG7yVc9PzT9KhkMY0U9sBznLy7G9XoKU2twP27mdb80zT/DwrLNU1U0JELZfKnY1lbqZU/XSGLAGNtzGzZa2w1QEiWpEhYnk816uyLkedYkOkWbjz1fyjUaoU3COlxDOqRP7MlEc=
  on:
    tags: true
    repo: ngeor/dirloop
