language: node_js
node_js:
- stable
before_install: npm install -g gulp-cli
deploy:
  provider: npm
  api_key:
    secure: "iEQ2NZXKZ26Wvf/kn2ZuzeySpSWQPm06hi/71418p8rYDTxZiacJ7TsGLHPnr1L582u73ASUUOymE2l6Ke2DnWK+rZS+54vhWNJh+5T9897t/0iS4fuPleExuvo
SZBNU0m6TrfL+NbLqWeJ5lfqH+r0WTKcqyeS1MKr2S9PV+xnsnRgEDqRHrElsu2fi4EDVNHMMAY+yqUe5Q9Ly3AMqsVxdlAHfxClquG6e5WDmHhtr+08UNpTm1Q8dSvAjG5HvA
CHAAptQ33EdhApdRwKsMsu5JEFG5mKIwV5OkCJobJm7/Az6/lF2vpzytCwcnU8FRP+TioIbVuz3dIuwt24VRLAnWooLqLwpdI0aUjIPOaZqEkmkjDEtXd+h+tGsOpt1XSGw3vi
LGv7MqsGnzo5fRSYE0eEyrHYUcImtXw0Fxz++AknJN0tTL0nLoW2cu78DDDOoeCu+8a+DJKPpf+Uiu8z8nrHpi0y6v0c4O5vKUtQCO99HYhDKHhwNrdVDtdFbMV7QcHxoDEZE1
rYFjrWqUWLuK8tKxFjHfKE6N5O5hmnq0f+T6S5x0AWY6b+JUnjqHy/4b6Ke1iYRUR8aheXkFCwaw8alkikuQbhQUeBiP5oSmtE4MQ1nZ5bRRwdZGcPoRUI7bx+3skJ8UQFcbKy
YZHJjpLr/7oahTWyPple4bt0="
  on:
    tags: true
  email:
    secure: "uoedTxlU3XuGBgxX8OqSAaE3swiHhT2ki9dUK7ZTMtS4RR4teRctztUCIVm0dLNYHm2LMverTFZeMYfcmNbCXn1gq7GKTXiI3hlkKv6O2AWBOhNwX/Frw3vVgk8
57PvfR376AbR3WPbtMRnxHmXRGN7uCiFM0bZFqQd6YlyUKusiHN9A6bkEyqNT/66kYLcf+BWo4iqlk7fuY7GSmTPrsHCHWjnO5RsWUPRqxzyj+Yd02ikyTNX5EGwg3m/GdlBZj
J+T+qWe/ZDDXqTVrnSzlpFT81OVIYnXAZnwfnIjICknQ42KS6W3g4iUW68kSdvGzUJfXVow1iZ8jBmE9Z5Zt1rTRIz6yiQdlQo2io0zpwPOTbtvnwGH3pQ3XAyd7zmt+RjzQ2h
4vpoBnuMPAdNrJBC5nJd/s9okriCyXZEprvjOLX6IUcXtx9YgoYRbOkC4yVXmR5fXKQhvU+JbIrDhhL+fX+0bGdbN1Yy8LEu8+SM6ZMNrgQfVpMIIlD2vh3ziKbNwRI6z7QaVW
fUACMCn6vSl19Qb2rX1q23I0Rakp1V9LBorD82C5lsKJAzhVXgjOkYHi3e+kJ+TEmdQXeCcHzkSDPlwJvNwcq+HNPPDw64x06wLZYptulcFfAThEX0bELo4TF3CykV1XXYtKGb
3TcsGDjEzFD71rIbS/neDVP8="
