language: node_js
sudo: false
node_js:
- lts/*
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email:
    secure: VxXtKKshFPcSM5RDOvkcVKtAWeW1wa9cbPGt6TsQd2FG8uNDwK3/lA2rzJQZ5Xqw5HV0ddPEk5Msmyde7KAB9tuV0hz9dl9qwfcjYOEUHC4uhV/m4LqLkjdu1QKI75SIFxVB+rZUmBAi938YdBMCvehV1GGaRKdrrKYett0dmTgdlZaOgthHh0HQx9B0Vs4dLziUu+Wx33lVZDU5aJbbtdZkaRoIxZrE9rqjLkonsibgKOvPnyIHIqHkwUwbPRRdq20v87leCvCGq8fbmzfBhOsf16ccdUcDPX4xlbIZV28JJGoaAmrzfUKUC2+GjH9Lmb2ld4vp8BtqC4dzlUgLuTbLO5CYaKY0BlwJxTnksvSjG7nmoh+lIlYVFgSIJJ5nKhhciOSSx7ZLIXmd/PO3q/Gy/iiiG/V0yauYQYrRKJ4YAJyZRfOROymaaKo6IelF0vtQ3UIM/eycRk9ueKJ04ms6bureO+VIILShsrYMR2jokE1QtevQpUKq1dNaNKy/46izsWPwKq1CGJXptaIVMna9B2qamABgRC48XzucLWbUU0u0Jn32Dco03AkeX/VConGQ3msQgQc3YAJj6QAps+j/k2jeab5qYUuSG790PsYI52JfkIlZO9cwvvBGaqOYuDIZy5EHimxz3hyoyutd2mNemE/n6PkeoowWYDIlvJ8=
  api_key:
    secure: PCLtoXGf2rmFM0CaxAsH66CYImsQURMZrGtjGmsEaAsKLkFienqTnl/bvudykdu67TDzBpJ3vJ5yj9ANgpHfUcFlNVA3VN7/Yf3lAtBWt+hOogW8PJpWyBIp+oqXRYtdw3FghpcRNxgIwZyWUZqjLTIaUaI3BVz9/i9IeewmigC9ErmhZ1+bYjm6Z/8nYjndyF9xqW8P94vOWDeMg6u1LRx4St3X4krpQ2D62RbhbzMplsYvJKVkf1ExwIyR9x20VenYSw8UuIHLbBlM9KlUcfrXl07Yx+/LYNUdpLl/NaktarRTGb82nMfMqh/vliTArS5ZMDBFtlumNXHHJF2+B8VkhHZjsHk6PuHLFmRt+tENPADvIbtRnmE66PFjyIWvhKhwCmDp+0GQakw3u09yZg3p8tXc8h7+jbdCzfzU9vrBB86FRBqm5/48dHPiFJuLQvtqyeNxJUBnRWOFNQ9U2TUSME/0MceuqzColl8LqWOuv0bjQvPhBSd1Uoy6+sn9Vwlh52rr/fDPLKjyBpoWwV72zoa/UOFPLQb57ex0rNoHpOutPMtOFZHOqFTQiZGfB4oxowuFSsqMaD26Kgslh2iYk27XxrXBaE5v9mv3KqyDS2ow84B4Y4jJIL2YyiUOnLy8U89PaGwb9w4tggf+m2mSqewPVyqaknXsF+LWfUg=
  on:
    tags: true
after_success:
  - npm run coveralls
