language: node_js
sudo: false
node_js:
- lts/*
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email:
    secure: 1FMxaJJ0hQEKXTAehdr0L/7p7VY54gHM3EzTKbI3UakZyqPHMdDW51GDWS2Jo5J3MqQ1GtJyr0GPKCMaT3nj1IO+qM67Y3AUaPMNCR7ePJAcdEGs4FndKPM6vqmgNY9hHzN/CiNfky5JoeKzB5GSIuQkHFdVJI9Ie39PSErhGC4UzxjoJTZ0VPR5j7yCONBCGxm1Fvos/rD5jGJ5xXJ8GfF23vsaqM06F7ZljnRIPr3ZKfeR/5K5UYAVEBFAWfMVlkwnOv5qY9tp9vgWe2wgJbmYZxrYEGfA4z3UHMJ+FHzjjRB84/PVURVzAA5Bq1sYTM6S01oCjORMcKf03vy8U3j/lcnBWwUCv/2iHUHUMgVkfvrtQKTWaEoGBbnSjpfw0lUwCpc78XLHCYGVGCPLo3pXyf5SrBOmx7VMquGipZN0RLhGBR8Y2gxneCAG9/+itUyAUWx4+u+PDGcrYcHSDZbxYkpwGIqyv4e0ZMducwOe22mlpj6Av8Zy3+9Y2C4u5fTSElp+5SAsyw73wHYJF2Ow1Z8HMTuiIjEwMrfR+OC5kHek1jVw7R0kvYGSYSvmySmwiH3miPVTTaOwxnkqJZot26ZTTVpz5jJ9Vj2GyuOcRGIcIrg3qyCTzqddpEmblvonbphoqe/l2Pk4lL756m4j5lgy/YEpueSteGltsA8=
  api_key:
    secure: JdDR6bOekWkAiaKMCp8P0l5ub/0XSRi1JeQawOOKQ3kbSdYdoVniEoTmxy03MDven+bWwd7+q5O2R/fcjgmwyS4nXSivjPVDcJoeN7dM4tEXWs/rDz+lJrcr2QCO/G5KHvyA86kx6LfL+LhJw98NV2LOShTAQW1wvd/lcGfMP4ffI0D/Hd9h+NJnvStnbYwXHj5WlNwtqjJjQuVALX2w6VmeY9AKoyqO92f36h3j8gxM5VzTDXQQl+Va6J/3io1hi6CopKyWtH5faLFNxrJMlf2KBKd3fqO874xhwe5GdqlnB8JVB6NmmLnbTJkv90PKLyj7aUQoiwqcaTOSPMbcgolpvqWBAbP/O4ISpOtiJxhwcNkVNLPzISPYU4ubwpmMV6MOeJxb8tTxbYXv+xyAdldtgKuRLC2rgqjL2kfIU+7sSAdmbqg/r0frCutiFnTYuqtqVJ2jXBSSBzV4uXddb9hMmmXrKisAxv3bSn4DVxCiKC0og2mKq1fVMBsgsb1aJ8VQhnWNhwlF9J2Mtb4yuGXVc3AgNvot8VNwAeKDBnIgOqDGU0JeqIbLoThoYVPKmNAy68GxW0LOWywnmq8U4UH2VvVDT2/HGdJLDODyavg5VPZQi8oZ0i8tuSjKw0jgjpDw8vFnYubMy/bxp5EMosNVrHejv+JPHMzY9Ah5sOA=
  on:
    tags: true
