language: node_js
sudo: false
node_js:
- lts/*
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email:
    secure: pL0vFLHyAIPnpO5SLYwYdYXm0cNahOfGpRdMNj753DFhIefsIJNPRVgV2et/txGEyygd0KRP5Bqna2ATQh7Aj2+BS+p6HnpSCTipyWfJRlk+T6xmTQ6zf9NDs/84k7vxvzht5qTQtsknDuX3G3k0ZBh6gQyD309vp/FjGVjhDY7vcNyFWOhhglBQ+nJioo5jPUc7Ar1IAXPsYqqFc/wgfsFWSTQ9eeKSW8c28FRVjkU0iliSgLHpsdqslpQfmgRHDgwkflh+fS9peycoQW2x6GxWYhT+uRb9XMfN5Z3RBVZeB0VY/tU3QCqFBA76m4q8LR9xql5PlMp1BhhPtlthJDg0aeuyLrnU1+Dp7ipbf+L0KBuZDCO+c2HZCZ66waSWqFnzQ3wRDEbRIML8Jh8HHT5Z40ulwJB1QsC1ZgxplcjMvAwbJFTXYUn+fltxBZ/Z1oHrkKHns9pHReXvqle7xsQuYOB+YsuMVqrihe4FL07A73YCpZTXNKg+ZjZHHjdP1QMJg7CKXhcAztuzioyzp9KP7rN7oArygkdZPAHdbp8r5ytYgcVmTYG9+63rc5mg11V8Zq3Grxg8Ab+hsvihYtty5iVVYINX8fJXhzDJLLLoQhIXbTZCvsDgZXdkxfXVQVteu3vOEm1a7CIYWfkm5O5fEb1f1fTXtnjWwI1Z8cg=
  api_key:
    secure: cvnPJ2jlBm7zpSMy+ygzGzSv4T7ViDjA1Q2p2Q461O1MOvnIIIWfiawQSY/teABp9sJhDaz5wTSfpRBBWOR3MuvI/2qXSnVpR2I2f3gBkThM7q9w6FOwrS+T5i2+qbN0DExHGNTPfVfMsv+ExCO53V9FpcIrwpSL0NFZgWEtYrEw5r3LRe89IDTlJIo0o7+aniMDXxBcp4ZoxqZh1O/Np1AMA1TI4zmo10a65xAKACs6aMadiXLVc4IlXuz+522TVN670W4aBCGyJi3JWvkvJvwS0+rOSPeZbUmovlvR+PIDAwrCqCfNEvYVJ1trUn61H1lOvjSgRTCzV7OoFny1gUJ93dVpdNdrK+SjqT8Hk8EennJBTMCUnmSKyAVt9wfnRh+6ibT0yy9dRmi4Fy3jd6Cht6/Gm8iIE3jqGwmyo6V0qJJqWJQ2uy6b4nMki/bm9HjTbPW/yiMMrx/Mp5pZ59i5XLMI9xbIQdtIaqDHtZ4l8tn2Y7kApl7dqRMJAfm2KgxoGRwB3vr8ElFtBqbXmCkgFH+QU1NRd32a7TDc0bHhPf3UbCeK6r8mIZ0LOt5FQ/Qq7tTwExhCaBocmcxEIP4WXV9K7hUWb73+M69NrHhh+5S8F8UTY92ddhIKbUM+cE0IjsB5DNSdzhnzJyadWmoEDfn1jJhHxOVYY7OMq+8=
  on:
    tags: true
after_success:
  - npm run coveralls
