language: node_js
sudo: false
node_js:
- lts/*
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: Nikolaos.Georgiou@gmail.com
  api_key:
    secure: U0d4VNQwRVDAF2iRIStDQPXh0VI0Luf1O5fmHIvwjPKTxasz4nADn6D6q9zZE+Ns+1D3QFA3qa2P+hJo3dpmUHz+H7DMBSqGr7MfB2rmENBE7efFrho0kNENcPVD/MGkrF0ppIIv75DJO6uU1Nv3xb5Vm8/pAyhy2hMZOXAFUI79elPjfDTeBD9eFPjBXBoHPBAgFrrmKBafSjiLv+jKxmhbsqjq59mx/TNiSdX7vVsKHLT2Xry7zhWZl0iGPJgghhf69OI7AJR2jIiGVyoPwfLKc5wdYVv1ETlxFR76JXgnu+mOyVlZkOOVq6PZ9SVr9q0CiUTUnGR6O6aEHCzuVilGRjOKmFUa2cd8GHa5M1reC3Aa7lkTCkC+PdfkNG5gMLQBUHCpwnHaqTWKUM7NPK1zrPvXzFjC6TT5vdJgx10EarX6Ct6VvyQ339814InyLdVTxt3vmxDI8bEB89BafgnpTcqnRv9kx8iTuDoxMJIeciuddF7u+yKlsz9XXftmNvBmz9YRXdtxWrgSHNThSV+YkwNXaJwQIb5MgKXxqhbb6F5RrZo8I1Qevlq+55pdcLD3BgSSxg9SStYROcobLMQvSjnowKsbXHD8DG7lRSQo0JycRlcEMNiqDx0PuWzdVU03Zu1FXMFkSSbjteFcWYBTJkUjN165jXwflf9lf60=
  on:
    tags: true
    repo: ngeor/generator-csharp-cli-app
after_success:
- npm run coveralls
