language: node_js
sudo: false
node_js:
- lts/*
after_success:
- npm run coveralls
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: Nikolaos.Georgiou@gmail.com
  api_key:
    secure: ZvSdPTrWOijBtm0oNWAanoGYfQ/C3SgGbFnhunEKM0gS9ATGuVRhcVKvH4PK0Jwo02GDElpSHOUGw601LTDT1bmJPOeukMvCh8DSQDuyyHpp5F88cGlJECsoYIGXk/CoROX4ab+hrsF4u9WYD3pETznGHQNCMxhV79nd42HKyvcaV8cFSEuYHTVdR3qQ5aI83/Dv6Vyo4Akz6wSNnVrvsIjV7qHOKKwFdlyOeCW70n5KZRCuQlNxp/bI9RI7xDGKw/amwYmOq1hgCZi5HqXntNOIJGHuxRHdy9dDk6pv9FsY9qHIVhqauugwCI+NsN6lUoMJuVb4DLPhwk/4zi78tvm5q22CEadBfYrbOG3f2DmYC5LdC6xz6qnmwh0n/Xj3u0Cz/VUAbTYwfwnY/aRQnOMy/qw5aKzKFD/l6KN/+uf+uIDNfPxmZpCqmxu7hBhng9mIH6Sv3+YVBva3SWE5zCUARpz/sZj0zyGqiVTcodwKR4e64efhRmUX38iHjYU+54cvdgfgROIJxpLjMKXcplTuJZ3Mvw4g6/x4xebIIzYPIhIH+6GM6b8yG4hPXleGL4138kpgsp9gEOorK83xYjp4dDZooBSNzYayPY3auHuIfziEai2Gc1zb+mTgSFh++TQRmnuBm5cgcaBub0wFXVUz5Y0fAvh223dy14PsDPg=
  on:
    tags: true
    repo: ngeor/clone-all
