language: node_js
sudo: false
node_js:
- lts/*
after_success:
- npm run coveralls
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: Nikolaos.Georgiou@gmail.com
  api_key:
    secure: Rzno5IMULibGSifNswN1ZWHyu9toKmlQ/xVwtES2GgkEuNTPVnJOgBLkBiNldDPqCMTEWA3L+Ph9DrwRmGj+c6UwHAjC7IzeiSYVEvX0wKayNRanaPFwF6dCpHJC+r1AVnmFsuwJL8Tde10fpXvZNUyY0sWDXJjiwWJsw2Y4cGa4m/M6DhOaSfv8Z7l1wL/UMjKcXoY3/f06t/u7HTVBYknY6/0GExMLNBA3LT2fVazW3y0EbyBataMYtz/z8dNvQFT00JxcqTVbiaW4qBkVGPfhWJUolNiHQOe4HVnVk87vk0Y9PnxsoUm7Tr61pEtfkrDoe5ZhspkA+aW/2whHJ5xXM+W8wK/ELqhEgtGhR754viM+tte1/KTggHepMFcxzwAl5+Tcwxx4LMgTyuE/S+3FrR9z7Xet27FP2qUiY2BUbPiEjzVpw7jsakaXfRc67DnapXuWpZFBNGEod50obUKBqXxm4toOWslenvmJw95AGq15iTdq4aSKPIn+dP8RxhWgHBBJm3O6uu7EtIph3WUGzSYz2ub44xwfV5K6D+Rqpm+vIX/metHIhPh+nMXLYTno5OJx+2pTOlwO9F3xRG9CWmwdEsZepcqnD1zds7Q7lKCtQu3Qz2JgggyBmm4MWVdXxotL0fI8JnXDAOHf1Q5ZibCipPgGPvzAM8cToh4=
  on:
    tags: true
    repo: ngeor/js-cli-logger
