language: python
python:
  - "3.6"
script:
  - python setup.py sdist
deploy:
  provider: pypi
  user: ngeor
  password:
    secure: Myg9EOH1ShJGevBLAuxzSya4XOHA2dTJAmiP1BbcmBrPeh54WommE81TCVqk1XowYNWfafRZW1NWPJ+a3++w1udyKbvPq+QqOwDxL+zpV5TUYu5Fo0+Mx48QPZk6RqC80I8DB+AgyKlnHglCCsMof5iS60eYuzC1gXSPBGfqwNZ16l1EhzPkDOKxxUDv8BSJjCxCwn5MEHcp7H6QqWbYXVA3PmVmpaj+vKn9zR3nxFLLcUDMnj8CrdVxgcInuKamKvyU/GzUDPo8R5A/ZWBH0FenyveXFLvB+oi5ZGsI1VxRgsuVvxLq0BON/z4pTt9hA6ORIycnomiONU/tN7f3l1+Jt+rSMJ0jQy+E1Oyn01hENR1DaP4qX+N8res/4mH5Bb7XvfD9NjpMseQj+VVga7HC7r2TXeruFy98X0PjSl8FK4laGMgVvr/IN6cUeFaiZ2ra2pH467+g5q3Ca5QUnjFm+1y/Mk5RRoD/RbjD/EgVoe+hDhvsQSlc1szRs+1WInXG6kW2J4u7Utlr7PSep+Vy4hf+w7WLgrddhhWPtB56OgB4p2DNbwnee/cZ1bJPu4V+fikChSMpM+e8/yFxCiOExYRbZ7NMset/slvYIvHruUobA9m2JvgcZfkrHom4xLHSyrm6n7XacClzo8bW3gsqdSoQFjoUM4GPpNf8ygw=
  on:
    tags: true
  skip_cleanup: true
