language: node_js
node_js:
- stable
before_install: npm install -g grunt-cli
after_success:
- grunt coveralls
env:
  global:
    secure: mi3iXJ74o2N7kS5g4KjpYXPYTGQ9clGvmIwRiQ9OXidMYsWK1KIW6idlPdWOntB4vWRFDw2jFwlsVmYP8j/I2ppnIrH5ujUAR9l2kneHiIyhq3Uz+fdJW9+vPkQ+3pjcWNbqfqoXL5R67SnaqQckknUxy2y1JBsCEtCT9OPVfIqJf5RAoHrxvssBCwuiNjEWJcTRtrUZI1D47zJBodovj6QdZBoM6F9VOaUU474oJGYG+zuRetYk48iL06oDODmeUTaJPLC+j93V6e36xAI8KsHSi1rz8skw+HiGzjAnleHJO76y7QfNB0rLpluabiDeXPLNWYpDYSef2rhBGeuViafR4nPKF4FWXSlWt14GM5oeBrV2MguKZcMcaV41eoi3oFOqOuQz8xEUhGTTUVzZbApzdmJAMQauDrboDgWxNYPPdFaxorBudT+K34yVppn52oF6/R47u2ucyIzPDn+Y+IT6WZ1RYyCtd/ce7s/EtsBiGwSqZRkb1up15mOaKcQppL5YZUVRo5yWN1CcFt9ho95vtH6a8oLuILxcmNTXYV3RmX4TKktlhrHaitFE3/X/I3HRWSVz2VercFaW+Z1DX/Tybkhkwr4vhagLWcjwfezWbrz58kNvby2kqKixypDPI5PVck4iHop1/RE5eXSOIJNoDNOyOn3AGd5tFMWBeJM=
