language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
script:
  - pylint *.py
  - pylint tests/*.py
  - coverage run -m pytest
  - coverage html
  - coverage report
  - coveralls
