language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pylint coverage
script:
  - pylint *.py
  - pylint tests
  - python -m unittest
  - coverage run --omit='/home/travis/virtualenv/*' -m unittest
  - coverage report --fail-under=95
  - coverage html
