language: node_js
sudo: false
node_js:
- lts/*
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: Nikolaos.Georgiou@gmail.com
  api_key:
    secure: OGZBlYdw/o52SNs8jjMVrGxAjZiYicKOR6EmttVA88+2/BKgw1zZO2tafiFzmcBxzv43JyI/m6mxcbyLgGqhWFK3aphlnsWHIM4wjF6dcDqhuwPJ+hM2vzGynmSkbF4P3AurTbPlFp2alQmwQGhfk3iuT43CvyKBpmm7UcD6LejKFyJ03Z5CrJgr+4ZgTiYy2bCucX8uVAJyzUrnI8WTzmzFamFrcrTNKyWCBVRj0zaWoID/FltGVOvqDtaYXm2rq1CVsuadKE6T9KCq6aaCRTJrliLXJ5MUuiSrKjqb0g0L0TMHOJ0Sv8lLEf7uwhiZ80k9SwQbJxxH0GRxEPzO3mbKPvfn1TDrxKkH21kQS4J2geqIreFyo4rwv9n2k573RqqOf6Ryi3+5NABOR28LKYY201lIt31GxCOJSlqADCuW/x63MDL09lnQcyVeoc80rkUCxM3y1VYhi3IppsbdGeVosR+HZOwTuw69oH4JMdBr02/mnOCHnrKmcEqXKNJHoUJsfvougZ0opbrZAudzDccIQva44S1TCMpln1HuH4K+UGQVk7w7rYAXZq14eVii3yy/tYVMMlp0Ri2FiC7iywTkJXtxFbV56EsP6OTOUc8JtDizRMzjBZuc6QPttPUNL8EAuj1OXRYfubQtowUQiaXplf8mM93PdCDJ53G4q5g=
  on:
    tags: true
    repo: ngeor/generator-csharp-nuget-lib
after_success:
- npm run coveralls
