language: node_js
sudo: false
node_js:
- lts/*
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email:
    secure: 1FMxaJJ0hQEKXTAehdr0L/7p7VY54gHM3EzTKbI3UakZyqPHMdDW51GDWS2Jo5J3MqQ1GtJyr0GPKCMaT3nj1IO+qM67Y3AUaPMNCR7ePJAcdEGs4FndKPM6vqmgNY9hHzN/CiNfky5JoeKzB5GSIuQkHFdVJI9Ie39PSErhGC4UzxjoJTZ0VPR5j7yCONBCGxm1Fvos/rD5jGJ5xXJ8GfF23vsaqM06F7ZljnRIPr3ZKfeR/5K5UYAVEBFAWfMVlkwnOv5qY9tp9vgWe2wgJbmYZxrYEGfA4z3UHMJ+FHzjjRB84/PVURVzAA5Bq1sYTM6S01oCjORMcKf03vy8U3j/lcnBWwUCv/2iHUHUMgVkfvrtQKTWaEoGBbnSjpfw0lUwCpc78XLHCYGVGCPLo3pXyf5SrBOmx7VMquGipZN0RLhGBR8Y2gxneCAG9/+itUyAUWx4+u+PDGcrYcHSDZbxYkpwGIqyv4e0ZMducwOe22mlpj6Av8Zy3+9Y2C4u5fTSElp+5SAsyw73wHYJF2Ow1Z8HMTuiIjEwMrfR+OC5kHek1jVw7R0kvYGSYSvmySmwiH3miPVTTaOwxnkqJZot26ZTTVpz5jJ9Vj2GyuOcRGIcIrg3qyCTzqddpEmblvonbphoqe/l2Pk4lL756m4j5lgy/YEpueSteGltsA8=
  api_key:
    secure: KxUD0xVxOhIK1kahrxdgJViugPmWZyq/CwFrYPkkhFGhY5GjyzLk1KrgrAASFVhTdvVyq2jaYxtQC23GNuLx9gViebOQdeyfYvEIfhNLM2CjPbMRhBHZi3qKfD6YCAm9czZKL0hEdaj3ssb1RlI/aJjsz7GojV6lqywPApOVCILnOdP2saKrKDzVMpv0FdOFZfYxTFmlIYnc47jEajjj3NHyOv1c4CPJOedMSeQtwoPa/hG3IVNVvjskkW/+9zPVMQOurk3tewtZ4Ob5KZRUICUPsEGr7QHcAbIIT0YCOPUf4M80eapZepuG2+Mupz57wusrCXf8YbW6aKaNjAp5RPVlWNPoyEvLK10wuj2zITpmNOAYXTqLXziljgx6VvUD4cu6gCDaehV/FFrKhHgF32YICaEAkAbhxJuXJPrUu5VOmiwBccZJSXsB2yjk6R4cWLJLdQ3s5YLPdZB4B3rAPGvCrUFLxMrfNfLRSltRErn1RprEaJIpVL/lo644F5RlBdo0kxDMqxFKhw4AjHDh5Gx1Xv8Y6uDqUOj/g8Eh0xOodeucqOV8vA4znq7WbTFqwTE1utdrKDZCJmGlcjDWG6/rAI4iA6oFHD4X4djAzJowHW5zaQyiBejuRTouqwCjMX+X8wy2fQqh3q2c8wzpwa61I5bj+Skra/oNVNh2rO4=
  on:
    tags: true
