#!/bin/bash

# input file
IN="$@"

filename=$(basename "$IN")
extension="${filename##*.}"
filename="${filename%.*}"

# output file
OUTPUT="$filename-optimized-fuzz-10.gif"

convert $IN -fuzz 10% -layers Optimize $OUTPUT

zenity --info --text="Finished converting $IN, result is at $OUTPUT"

