#!/bin/bash

function process {
	local filename="$1"
	local newDate="$2"
	exiftool -ModifyDate="$newDate" "$filename"

	if [ $? -ne 0 ]; then
		zenity --error --text="Could not process $filename"
	fi
}

newDate=$(zenity --entry --title="Change date" \
	--text="Enter date time for the JPEG images" \
	--entry-text="YYYY-MM-dd HH:mm:ss")

if [ $? -ne 0 ]; then
	exit 1
fi

while read filename; do
	if [ -n "$filename" ]; then
		if [ ! -f "$filename" ]; then
			zenity --error --text "File $filename not found or not a file."
		elif [ ! -s "$filename" ]; then
			zenity --error --text "File $filename is empty."
		else
			process "$filename" "$newDate"
		fi
	fi
done < <(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")
