#!/bin/bash

function process {
	local filename="$1"
	exiftool "-AllDates<ModifyDate" "$filename"

	if [ $? -ne 0 ]; then
		zenity --error --text="Could not process $filename"
	fi
}

while read filename; do
	if [ -n "$filename" ]; then
		if [ ! -f "$filename" ]; then
			zenity --error --text "File $filename not found or not a file."
		elif [ ! -s "$filename" ]; then
			zenity --error --text "File $filename is empty."
		else
			process "$filename"
		fi
	fi
done < <(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")
