#!/bin/bash

function process {
	local filename="$1"

	# separate initialization because local sets the $? to zero
	local dates=""
	dates=$(exiftool -G -s "$filename" | grep Date)
	if [ $? -eq 0 ]; then
		zenity --info --text="dates of $filename:\n$dates"
	else
		zenity --error --text="Could not determine dates of $filename"
	fi
}

while read filename; do
	if [ -n "$filename" ]; then
		if [ ! -f "$filename" ]; then
			zenity --error --text "File $filename not found or not a file."
		elif [ ! -s "$filename" ]; then
			zenity --error --text "File $filename is empty."
		else
			process "$filename"
		fi
	fi
done < <(echo "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")
