{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "teamcity.serviceAccountName" . }}
  labels:
{{ include "teamcity.labels" . | indent 4 }}
{{- end -}}
