apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "teamcity.fullname" . }}-volume
  labels:
    app: {{ include "teamcity.fullname" . }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /mnt/sda1/pvc/teamcity-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "teamcity.fullname" . }}-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow
  selector:
    matchLabels:
      app: {{ include "teamcity.fullname" . }}
---
