package BlogHelm.patches.templates

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with uuid = 'bdb9db38-14a7-4b33-a762-f84f97141b1c' (id = 'BlogHelm_DeployTemplate')
accordingly and delete the patch script.
*/
changeTemplate("bdb9db38-14a7-4b33-a762-f84f97141b1c") {
    check(buildNumberPattern == "%build.counter%") {
        "Unexpected option value: buildNumberPattern = $buildNumberPattern"
    }
    buildNumberPattern = "%dep.BlogHelm_CommitStage.build.number%"
}
