openapi: 3.0.0

info:
  title: Partial models of Bitbucket Rest API
  version: N/A

components:
  schemas:
    Link:
      properties:
        href:
          type: string

    Links:
      properties:
        self:
          $ref: '#/components/schemas/Link'

    RepositoryMinimal:
      properties:
        uuid:
          type: string

    User:
      properties:
        display_name:
          type: string
        uuid:
          type: string
        links:
          $ref: '#/components/schemas/Links'

    Participant:
      properties:
        user:
          $ref: '#/components/schemas/User'
        approved:
          type: boolean
        role:
          type: string

    Pipeline:
      properties:
        uuid:
          type: string
        created_on:
          type: string
          format: date-time
        completed_on:
          type: string
          format: date-time
        build_seconds_used:
          type: integer
        duration_in_seconds:
          type: integer
        state:
          type: object
          properties:
            name:
              type: string
            result:
              type: object
              properties:
                name:
                  type: string
        creator:
          $ref: '#/components/schemas/User'
        repository:
          $ref: '#/components/schemas/RepositoryMinimal'
        trigger:
          type: object
          properties:
            name:
              type: string
        target:
          type: object
          properties:
            ref_name:
              type: string

    PullRequestSourceDestination:
      properties:
        repository:
          $ref: '#/components/schemas/RepositoryMinimal'

    PullRequest:
      properties:
        id:
          type: integer
        description:
          type: string
        state:
          type: string
        title:
          type: string
        created_on:
          type: string
          format: date-time
        updated_on:
          type: string
          format: date-time
        author:
          $ref: '#/components/schemas/User'
        participants:
          type: array
          items:
            $ref: '#/components/schemas/Participant'
        links:
          $ref: '#/components/schemas/Links'
        source:
          $ref: '#/components/schemas/PullRequestSourceDestination'
        destination:
          $ref: '#/components/schemas/PullRequestSourceDestination'

    Repository:
      properties:
        uuid:
          type: string
        is_private:
          type: boolean
        update_on:
          type: string
          format: date-time
        website:
          type: string
        fork_policy:
          type: string
        description:
          type: string
        language:
          type: string
        type:
          type: string
        has_wiki:
          type: boolean
        full_name:
          type: string
        size:
          type: integer
        created_on:
          type: string
          format: date-time
        name:
          type: string
        scm:
          type: string
        slug:
          type: string

    BasePaginated:
      properties:
        next:
          type: string
        size:
          type: integer
        page:
          type: integer
        pagelen:
          type: integer

    PaginatedRepositories:
      allOf:
        - $ref: '#/components/schemas/BasePaginated'
        - properties:
            values:
              type: array
              items:
                $ref: '#/components/schemas/Repository'

    PaginatedPipelines:
      allOf:
        - $ref: '#/components/schemas/BasePaginated'
        - properties:
            values:
              type: array
              items:
                $ref: '#/components/schemas/Pipeline'

    PaginatedPullRequests:
      allOf:
        - $ref: '#/components/schemas/BasePaginated'
        - properties:
            values:
              type: array
              items:
                $ref: '#/components/schemas/PullRequest'

paths:
  /dummy-because-openapi-requires-a-path:
    get:
      responses:
        '200':
          description: dummy
