language: python
python:
- '3.6'
script:
- python -m unittest
- python setup.py sdist
deploy:
  provider: pypi
  user: ngeor
  password:
    secure: BY05UUccuwo7ysQKE5JGqffHmCiZKHbnFRLYvBWScxrHcaMpXwP9KGp9ou6H5vjtdhvUuUKT0kKAauucyfWI/9RIMZ/GVCAgE/KkXOCWM5vj+/rvZ70d79RXOqV65TbB3CGLOUdjPuYvBXcpDYv91UCVLQ67UAD4rmJi+HWsSHhajV6bHnA1mE7eUsWpsBjGNQnndyjWzryH7NZN99VKy6QE1M9xBqsY9gp1BWGEAjznjVVHE0+SEBZYUzSfwP86OyXpHaD5hp8jYNz9xEPVSHiL5Gu7uHJ8AlawCLmUOgEnmEhRpHooNbj/7PH0EFrBYn4+dStUfkmqrLCgfOQJXRfbyQGPxP8yVRnFG1xCtQjmMeykNQ9aEyWj/h1gYNWyJLUeePop+hyaAhS0t21htjDoyNl2oKP1KiI0/tH2BAi0O8x1L4Vu3dRUuGHGZT8mj/A7fckG3qQnHos52Vp+5LuonTage6dTHr5VSeZF8vdqd7thDdMIDXBYBQBXsC9jeX90Bu8PVh3HfRG+AdXo6K3sNZQvW6bpA61QgrLv8BB3zigRTgnmifvMZMCb2pAn8V7iQ+A2pBBxdInbGxEq4A6cN5ol4kHXtbeQuhhG0sz5YTrlaTi+Wr3gobdB/AeIPfB3VKsw6cQS+xFJW01tlCjaCxlc0tz/6248E3Skp00=
  on:
    tags: true
    repo: ngeor/version-ci-bot
  skip_cleanup: true
