language: python
python:
  - "3.6"
install:
  - pip install requests requests_oauthlib pylint coverage
script:
  - pylint *.py
  - pylint tests
  - python -m unittest
  - coverage run -m unittest
  - coverage report
