language: node_js
sudo: false
node_js:
- lts/*
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: Nikolaos.Georgiou@gmail.com
  api_key:
    secure: T8LuuJqE9xWiSMf/FVDxBsPCFiVAjQxoB/7VMifBfNqQIP6kdCOHT0H3BZSjy77qA53pL2xMyfDB4FYvIohJbKM69QJTbVjP09Bu6mBs99nz7cQyFn7B7kFB5CwAnqhyKpu3Q+mbFjSwoMGXGui0ZynTzWnOYrJtAWtLySetEhy19X23A8dpA5QXbm/FSMfJITm9lll92EriaJJ1nZSZg4y6W1ou+DeXG0W0ymrJ8KwB0gKhCFg8jHhF+rBgQG/sx9X1ZwuJCbEgTdRBIEGHn8a6kP3I/es02ojuDHX95IP4pAxfuE3+MiXA7JjS133jz9q7lmBdo2NGU0/5s7Hb4wEfqW1gq647b1zB/fWIJ50R/YpEtlONsAjqE+uPEKPnxXbZU+msuAezCfx/39rg2HehBgoFKi1Bd1EV8EvnMgFg+ObUdrenUH2xxvPoIAGRDsB+QdV6BrPcAM1IPmjVpDXXQCO31d7vOvoXPMv33AC1M6TQRGujwhzhhZnCtPWZoYfqYWNUdniIFIHQwbqQegEYlyECR7XyifTQotYrLt2+YcjrL7EfU0f8FNWX6y6my4RIkbfwiQ8I3CEo1h2KK/XHxFCjx63Rvd9Ivwj+bIOsdhJVB8Th9J75+GyDWgBIqOivXr/HZ2c+/i3oo/Afiu6jnkjxVcRmrwcB8D8FsLU=
  on:
    tags: true
    repo: ngeor/generator-csharp-cli-app
after_success:
- npm run coveralls
