#!/bin/bash

# input file
IN="$@"

# output file
OUTPUT="$@-resized-440w"

mkdir $OUTPUT
for i in $(find $IN -type f); do
	o=$OUTPUT/$(basename "$i")
	convert $i -resize 440x330 $o
done

zenity --info --text="Finished converting $IN, result is at $OUTPUT"

