package BlogHelm.patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'd3c230cf-b4cd-4a9e-8017-4b4b945b3a3c' (id = 'BlogHelm')
accordingly, and delete the patch script.
*/
changeProject(uuid("d3c230cf-b4cd-4a9e-8017-4b4b945b3a3c")) {
    expectBuildTypesOrder()
    buildTypesOrderIds = arrayListOf(AbsoluteId("BlogHelm_CommitStage"), AbsoluteId("BlogHelm_SmokeTest"), AbsoluteId("BlogHelm_DeployTest"), AbsoluteId("BlogHelm_DeployAcceptance"), AbsoluteId("BlogHelm_DeployProduction"))
}
