package BlogHelm.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'd3c230cf-b4cd-4a9e-8017-4b4b945b3a3c' (id = 'BlogHelm')
accordingly and delete the patch script.
*/
changeProject("d3c230cf-b4cd-4a9e-8017-4b4b945b3a3c") {
    check(buildTypesOrderIds == arrayListOf<String>()) {
        "Unexpected buildTypesOrderIds: '$buildTypesOrderIds'"
    }
    buildTypesOrderIds = arrayListOf("BlogHelm_CommitStage", "BlogHelm_SmokeTest", "BlogHelm_DeployTest", "BlogHelm_DeployAcceptance", "BlogHelm_DeployProduction")
}
