package BlogHelm.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'd3c230cf-b4cd-4a9e-8017-4b4b945b3a3c' (id = 'BlogHelm')
accordingly and delete the patch script.
*/
changeProject("d3c230cf-b4cd-4a9e-8017-4b4b945b3a3c") {
    params {
        expect {
            password("docker.password", "credentialsJSON:6a39fd43-0513-4ba4-a446-14843fa7c355", label = "Docker registry password")
        }
        update {
            password("docker.password", "credentialsJSON:175b2d15-2353-475e-ab70-571d1e5843e9", label = "Docker registry password")
        }
    }
}
