language: csharp
solution: SongMatcher.sln
install:
  - nuget restore SongMatcher.sln
  - nuget install NUnit.ConsoleRunner -Version 3.9.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SongMatcher.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./SongMatcher.Tests/bin/Release/SongMatcher.Tests.dll
