package BlogHelm.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '2c559e38-b9b4-4dcf-a79f-2faa91c9f5af' (id = 'BlogHelm_DeployTest')
accordingly, and delete the patch script.
*/
changeBuildType(uuid("2c559e38-b9b4-4dcf-a79f-2faa91c9f5af")) {
    expectTemplates()
    templates = arrayListOf(AbsoluteId("BlogHelm_DeployTemplate"))
}
