package BlogHelm.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '2c559e38-b9b4-4dcf-a79f-2faa91c9f5af' (id = 'BlogHelm_DeployStage')
accordingly and delete the patch script.
*/
changeBuildType("2c559e38-b9b4-4dcf-a79f-2faa91c9f5af") {
    check(enablePersonalBuilds == true) {
        "Unexpected option value: enablePersonalBuilds = $enablePersonalBuilds"
    }
    enablePersonalBuilds = false

    check(type == BuildTypeSettings.Type.REGULAR) {
        "Unexpected option value: type = $type"
    }
    type = BuildTypeSettings.Type.DEPLOYMENT

    check(maxRunningBuilds == 0) {
        "Unexpected option value: maxRunningBuilds = $maxRunningBuilds"
    }
    maxRunningBuilds = 1
}
