package BlogHelm.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '3f8adc5d-5b14-4a13-9ecd-70b624f828de' (id = 'BlogHelm_CommitStage')
accordingly and delete the patch script.
*/
changeBuildType("3f8adc5d-5b14-4a13-9ecd-70b624f828de") {
    check(artifactRules == """
        blog-helm-%env.IMAGE_TAG%.tgz
        *.txt
        helm/blog-helm/values-*.yaml
    """.trimIndent()) {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = """
        blog-helm-%env.IMAGE_TAG%.tgz => artifacts
        *.txt => artifacts
        helm/blog-helm/values-*.yaml => artifacts
    """.trimIndent()
}
