package BlogHelm.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildFeatures.vcsLabeling
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '3f8adc5d-5b14-4a13-9ecd-70b624f828de' (id = 'BlogHelm_CommitStage')
accordingly, and delete the patch script.
*/
changeBuildType(uuid("3f8adc5d-5b14-4a13-9ecd-70b624f828de")) {
    features {
        add {
            vcsLabeling {
                vcsRootId = "BlogHelm_BlogHelm"
                labelingPattern = "v%system.build.number%"
                successfulOnly = true
            }
        }
    }
}
