package BlogHelm.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = 'd555deaf-076e-4997-8756-95da85e8d785' (id = 'BlogHelm_SmokeTest')
accordingly, and delete the patch script.
*/
changeBuildType(uuid("d555deaf-076e-4997-8756-95da85e8d785")) {
    dependencies {
        add(AbsoluteId("BlogHelm_CommitStage")) {
            snapshot {
                onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }

    }
}
