language: csharp
solution: IglooCastle.sln
install:
  - nuget restore IglooCastle.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory packages
  - nuget install xunit.runner.console -OutputDirectory packages -Version 2.2.0
script:
  - xbuild /p:Configuration=Release IglooCastle.sln
  - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./IglooCastle.Tests/bin/Release/IglooCastle.Tests.dll
  - mono ./packages/xunit.runner.console.2.2.0/tools/xunit.console.exe ./IglooCastle.IntegrationTests/bin/Release/IglooCastle.IntegrationTests.dll -noshadow
