namespace IglooCastle.Core.Nodes
{
    /// <summary>
    /// Generates documentation.
    /// </summary>
    public class Generator
    {
        private string nav;
        private string footer;
        private string outputDirectory;

        /// <summary>
        /// Generates documentation.
        /// </summary>
        public void Generate(Documentation documentation, string outputDirectory)
        {
            var rootNavNode = new DocumentationNode(documentation);
            this.outputDirectory = outputDirectory;
            nav = rootNavNode.nav_html();
            footer = @"Generated by IglooCastle.
<link type=""text/css"" rel=""stylesheet"" href=""style.css"" />
<script src=""jquery-1.11.1.min.js""></script>
<script src=""app.js""></script>";

            rootNavNode.visit(visit);
        }

        private void visit(NodeBase navigationNode)
        {
            var htmlTemplate = navigationNode.contents_html_template();
            if (htmlTemplate == null)
            {
                return;
            }

            htmlTemplate.nav = nav;
            htmlTemplate.footer = footer;
            htmlTemplate.write(outputDirectory, navigationNode.href());
        }
    }
}
