# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "k8s"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end

  # Kubernetes Dashboard on port 8001
  config.vm.network "forwarded_port", guest: 8001, host: 8001, host_ip: "127.0.0.1"

  # TeamCity Server on port 30200
  config.vm.network "forwarded_port", guest: 30200, host: 30200, host_ip: "127.0.0.1"

  config.vm.provision "shell", path: "bootstrap.sh"
end
