language: csharp
solution: SystemWebCompanion.sln
script:
- sudo nuget update -Self
- msbuild SystemWebCompanion.sln /p:Configuration=Release
- nuget pack SystemWebCompanion/SystemWebCompanion.nuspec -Verbosity detailed
env:
  global:
    secure: Gh8ARZFGD091cwbUKA6+B78XxobJDqnTHnjbbhEBUmt0cTf5et63XC0LQtXr5T4d6wn6ZpuECTaxyyH7eZjr9CeEzEglqAOz5Tade6ooQtqGl5oJ532XqsKeKYXp4GbXWV+qlm4PyitAfeDIR8GMGYXgdfOlObCJeWCCNFbNNImSBrn63SV55Gc3OlGcdb/6g8eskoSCNxNACCPXV8QjI10yHDXswLXIk9Avdv8Ute/X3JWPsf0WNL9DK9giYwd4sMxRf/D/CP51CDWdwxezW1d37qqxWu82R8gVh/boEc4SsmRxujX6auw+Ki2XoAGni1qnzxsM2kB4ZaYbi7nf/cTuI+mVThTzfT71Q+aGwV6XxjWOE/EOmhwhdHL1SFuflbKNC0G/NvhHLHO9UeerQjuUs1pPn+CXsiFI//pTgdhv0CT+VKj5/2HGSkJaUF/WXDkZFWLgsjk8530pKNqjVCKni1/zGvHy8GAZqjOj8E00dShlxAM7gEn4UEr4An4/ERoQ4b3Ju4vsjrGDWIqVzZ3QyEr9pw6dhZP4jVeGIR0ib3u6OiqcCpK1bQa4P1MK0XrPU5qJyl158klIRW5qE8fQdvLWyWjc9gblwAe3QIGLD5hRbtnAdDEQS0eFQvOWohAsawNYivPvfh+futdaiGjvTEQnSw1lrH44C/oyJEM=
deploy:
  provider: script
  skip_cleanup: true
  script: nuget push SystemWebCompanion*.nupkg $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json -Verbosity detailed
  on:
    tags: true
