language: node_js
sudo: false
node_js:
- lts/*
cache:
  directories:
  - node_modules
script:
- npm test
- npm run typedoc
- npm pack
- npm link
- yart --version
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: Nikolaos.Georgiou@gmail.com
  api_key:
    secure: yRAfb4vj6nTIGFzCEaiblQ47KXi1QcO0HIlu+Yu9hSQWMUqRCJSZycu9VMeiSSFhiyWSmJC+dOhCD6Q6O92L87+HJo1AWGZTmLhqT54AHUZp8Hy/DsmMWpqJJgyOabb8vbc/qpmyip49H5/GrO+5ni+ttmvQb8RgjfDFPmdjAgT3weHTN/VyFrSw2bfQeKvV7HXG8OKci4peb48738Zp+HDIOoAttF8Ewj/dJTD/tkpeDyaN14Y0ANlyD9p2/hx7yivoWJVWCbprU1dpYTNO+3YOm1NekF88R5ZMz1rXPVSM3H5mCEB3BfYUEXjzQ+A2Gcx4bCliClwcmNgjoJv6zieLxSMOuAFLrwvsxH1xd81r6YlFg/6ADaXcIadiTnR37+IlvEZ1UGoDBpVwqGMd/BZrrmX62OydF5ifGS145acHglaV0PO8q2+9kqqhp5BLeB4ONet9mULxNUsh/BPzJboD0ZUDMRNc9tPBota952zuACbnuA6ZUF5Kw5zXNBtnBgROVpti6QNg/GCJhxFTzTb6zIKHFYaqQWyK4cncKWREyYq1Gj/FiTgY4/TOKv7DipAvF9Apvk79ZAR3W9Xo4zdYtwcjHj6/Dh9WcGkqXGJLMpruZimFeaLD8Ghrv1BNxBDctqw0UvvqikkJMI4JrEk902bSRxZpQxBMJYWHzUc=
  on:
    tags: true
    repo: ngeor/yart
